export { default as FacebookSVG } from './facebook.svg'
export { default as GoogleSVG } from './google.svg'
export { default as LogoSVG } from './logo.svg'
export { default as PharmacistSVG } from './pharmacist.svg'
export { default as AddPillIconSVG } from './pill-icon.svg'
